---
# This Dependabot configuration enables automatic updates for pip and GitHub Actions.
# This config file present in repo on path '.github/dependabot.yml' takes precedence over the GitHub UI settings.

# After adding this config to a new repository, make sure to also:
# 1. Enable "Dependabot alerts" in the repository settings under
#    Settings > Security & Analysis > Code security > Dependabot alerts
#    (unless it is already set at the organization level).
# 2. Enable "Dependabot security updates" to automatically create PRs for vulnerable dependencies
#    (unless it is already set at the organization level).
# 3. Optionally, configure Dependabot rules in the Code security settings for additional alert management

version: 2

updates:
  - package-ecosystem: pip
    versioning-strategy: increase-if-necessary
    directory: '/'
    schedule: {interval: monthly}
    groups:
      pip-security-updates:
        applies-to: security-updates
        update-types: [minor, patch]
      pip-version-updates:
        applies-to: version-updates
        update-types: [minor, patch]
    commit-message: {prefix: 'ci(dependabot-pip): [skip ci]'}
    reviewers: ['tomassebestik']
    labels: ['dependencies', 'Status: Reviewing']
    pull-request-branch-name: {separator: '-'}
    open-pull-requests-limit: 2

  - package-ecosystem: github-actions
    directory: '/'
    schedule: {interval: monthly}
    groups:
      github-actions-security-updates:
        applies-to: security-updates
        update-types: [minor, patch]
      github-actions-version-updates:
        applies-to: version-updates
        update-types: [minor, patch]
    commit-message: {prefix: 'ci(dependabot-ci): [skip ci]'}
    reviewers: ['tomassebestik']
    labels: ['dependencies', 'Status: Reviewing']
    pull-request-branch-name: {separator: '-'}
    open-pull-requests-limit: 2
