---
- id: update-changelog
  name: update-changelog
  description: Update changelog (section Unreleased)
  entry: cz changelog --incremental
  language: python
  pass_filenames: false
  additional_dependencies:
    - czespressif
  require_serial: true
