# General rules for all TOML files, if not specified otherwise
exclude = ["**/.venv/**", "**/node_modules/**", "**/venv/**", "tests/**"]
include = ["**/*.toml"]

[formatting]
    align_comments        = true
    align_entries         = true
    allowed_blank_lines   = 1
    array_auto_expand     = true
    column_width          = 150
    indent_entries        = true
    indent_string         = "    "
    indent_tables         = true
    reorder_arrays        = true
    reorder_inline_tables = true
    reorder_keys          = true
