---
name: DangerJS Pull Request linter

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  pull-request-style-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out PR head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: DangerJS pull request linter
        uses: espressif/shared-github-dangerjs@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          instructions-contributions-file: 'CONTRIBUTING.md'
