---
# This workflow will upload a Python Package using Twine when a release is created.
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
name: PyPI release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  pypi-build-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |-
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: |-
          python -m build

      - name: Upload package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PROJECT_TOKEN }}
        run: |-
          twine upload dist/*
