---
# This workflow will upload a Python Package using PYPA GiHub Action.
# For more information see: https://github.com/pypa/gh-action-pypi-publish
name: PyPI release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  pypi-build-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |-
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_PROJECT_TOKEN }}
          skip-existing: true
          verify-metadata: true
