---
name: PyPI release

on:
  release:
    types: [created]

jobs:
  pypi-build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Display tag
        run: echo "Releasing version ${{ github.ref_name }}"

      - name: Install dependencies
        run: |-
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_PROJECT_TOKEN }}
          skip-existing: true
          verify-metadata: true
