---
name: PyPI release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to release'
        required: false

jobs:
  pypi-build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get tag name from input or Git
        id: get_tag
        run: |
          if [ "${{ github.event.inputs.tag_name }}" ]; then
            echo "TAG=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          else
            echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          fi

      - name: Display tag
        run: echo "Releasing version $TAG"

      - name: Install dependencies
        run: |-
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_PROJECT_TOKEN }}
          skip-existing: true
          verify-metadata: true
